// BookData.ts for Next.js 15

// Using dynamic imports for images to be compatible with Next.js 15
// Instead of importing all images directly, we'll use string paths

export const writers = [
  {
    id: 1,
    name: "যুবায়ের আহমদ",
    books_count: 5,
    image: "/assets/others/man.jpg",
  },
];

export const publishers = [
  {
    id: 1,
    name: "হিলফুল ফুজুল",
    books_count: 10,
    image: "/assets/others/ogrogoti.jpg",
  },
];

export const categories = [
  {
    id: 1,
    name: "আত্মজীবনী",
  },
  {
    id: 2,
    name: "রীতিনীতি",
  },
  {
    id: 3,
    name: "হযরত মাওলানা কালিম  সিদ্দিকী",
  },
  {
    id: 4,
    name: "ইসলাম ও হেদায়েত",
  },
  {
    id: 5,
    name: "দাওয়াত ও দায়ী",
  },
  
  {
    id: 6,
    name: "হিন্দু ভাইদের জন্য",
  },
  {
    id: 7,
    name: "খ্রিষ্টান ভাইদের জন্য",
  },
  
  
  
  
  
];

export const products = [
  // Hindu
  {
    id: 1,
    name: "হিন্দু মুসলিম সংলাপ",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[0],
    description: "এই বইটি হিন্দু-মুসলিম সম্পর্কের উপর গভীর আলোচনা তুলে ধরে।",
    price: 120.99,
    original_price: 150.99,
    discount: 20,
    stock: 45,
    available: true,
    image: "/assets/HilfulFuzul/hindu/1.jpg",
    pdf: "/assets/others/pdf/খ্রিস্টানদেরপ প্রশ্ন মুসলমানদের উত্তর ফাইনাল.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 2,
    name: "হিন্দু-ভাইবোনদের প্রতি ভালোবাসার পয়গাম",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[0],
    description: "হিন্দু ভাইবোনদের উদ্দেশ্যে ভালোবাসা ও সহমর্মিতার বার্তা।",
    price: 125.49,
    original_price: 155.49,
    discount: 19,
    stock: 35,
    available: true,
    image: "/assets/HilfulFuzul/hindu/4.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 3,
    name: "হিন্দু থেকে মুসলমান",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[0],
    description: "একজন ব্যক্তির ধর্ম পরিবর্তনের কাহিনী।",
    price: 130.99,
    original_price: 165.99,
    discount: 21,
    stock: 40,
    available: true,
    image: "/assets/HilfulFuzul/hindu/13.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 4,
    name: "পথ ও পদ্ধতি",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[0],
    description: "ধর্মীয় ভাবনায় সঠিক পথ ও পদ্ধতির উপর আলোচনা।",
    price: 135.99,
    original_price: 170.99,
    discount: 20,
    stock: 30,
    available: true,
    image: "/assets/HilfulFuzul/hindu/40.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },

  // Khristian
  {
    id: 5,
    name: "খ্রিস্টান ভাই-বোনদের প্রতি ভালোবাসার বার্তা",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[1],
    description: "খ্রিস্টান ভাইবোনদের জন্য বিশেষ বার্তা।",
    price: 140.99,
    original_price: 175.99,
    discount: 20,
    stock: 28,
    available: true,
    image: "/assets/HilfulFuzul/chistian/2.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 6,
    name: "খ্রিস্টান ভাইদের প্রতি জিজ্ঞাসা",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[1],
    description: "খ্রিস্টানদের ধর্মীয় প্রশ্ন ও উত্তর।",
    price: 145.99,
    original_price: 180.99,
    discount: 19,
    stock: 32,
    available: true,
    image: "/assets/HilfulFuzul/chistian/22.jpg",
    pdf: "/assets/others/pdf/খ্রিস্টানভাইদের প্রতি জিজ্ঞাসা.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 7,
    name: "বড়দিনের উপহার",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[1],
    description: "বড়দিন উপলক্ষে একটি অনুপ্রেরণামূলক উপহার।",
    price: 150.49,
    original_price: 185.49,
    discount: 19,
    stock: 38,
    available: true,
    image: "/assets/HilfulFuzul/chistian/27.jpg",
    pdf: "/assets/others/pdf/বড়দিনের উপহার.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 8,
    name: "নাজাত দাতা কে? যীশু না ঈশ্বর",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[1],
    description: "নাজাতের সত্যিকারের উৎস সম্পর্কে একটি বিতর্কিত বই।",
    price: 155.99,
    original_price: 190.99,
    discount: 18,
    stock: 25,
    available: true,
    image: "/assets/HilfulFuzul/chistian/28.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 9,
    name: "খ্রিস্টানদের প্রশ্ন মুসলমানদের উত্তর",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[1],
    description: "খ্রিস্টানদের ধর্মীয় প্রশ্নের উপর মুসলমানদের উত্তর।",
    price: 160.99,
    original_price: 195.99,
    discount: 18,
    stock: 20,
    available: true,
    image: "/assets/HilfulFuzul/chistian/33.jpg",
    pdf: "/assets/others/pdf/খ্রিস্টানভাইদের প্রতি জিজ্ঞাসা.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 10,
    name: "আল কুরআনে যীশু ও খ্রিস্ট ধর্ম",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[1],
    description: "কুরআনে যীশু ও খ্রিস্ট ধর্মের আলোচনা।",
    price: 165.99,
    original_price: 200.99,
    discount: 17,
    stock: 22,
    available: true,
    image: "/assets/HilfulFuzul/chistian/35.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 11,
    name: "বাংলাদেশে খ্রিস্টান মিশনারীদের তৎপরতা ও আমাদের করণীয়",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[1],
    description:
      "বাংলাদেশে খ্রিস্টান মিশনারীদের কার্যক্রম ও আমাদের প্রতিক্রিয়া।",
    price: 170.99,
    original_price: 210.99,
    discount: 19,
    stock: 18,
    available: true,
    image: "/assets/HilfulFuzul/chistian/36.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 12,
    name: "প্রচলিত খৃষ্টবাদ কিছু প্রশ্ন কিছু কথা",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[1],
    description: "খৃষ্টবাদের উপর প্রাচীন ও আধুনিক প্রশ্ন ও আলোচনা।",
    price: 175.49,
    original_price: 215.49,
    discount: 19,
    stock: 25,
    available: true,
    image: "/assets/HilfulFuzul/chistian/38.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },

  // Attojiboni
  {
    id: 13,
    name: "আত্মজীবনীমূলক সাক্ষাৎকার",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[2],
    description: "একজন বিখ্যাত ব্যক্তির আত্মজীবনীমূলক সাক্ষাৎকার।",
    price: 180.99,
    original_price: 225.99,
    discount: 20,
    stock: 30,
    available: true,
    image: "/assets/HilfulFuzul/attojiboni/26.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 14,
    name: "৩০ হাজার খ্রিস্টানদের গুরু যেভাবে মুবাল্লিগ",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[2],
    description: "একজন বিখ্যাত মুবাল্লিগের জীবনকাহিনী।",
    price: 185.99,
    original_price: 230.99,
    discount: 19,
    stock: 35,
    available: true,
    image: "/assets/HilfulFuzul/attojiboni/32.jpg",
    pdf: "/assets/others/pdf/ত্রিশ হাজার খ্রিস্টানের গুরু যেভাবে দ্বীনের মুবাল্লিগ.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },

  // Daoat o Dayi
  {
    id: 15,
    name: "দাওয়াতী নেসাব",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[3],
    description: "দাওয়াত ও দায়ীর জন্য একটি মূল পাঠ্যবই।",
    price: 190.99,
    original_price: 240.99,
    discount: 21,
    stock: 28,
    available: true,
    image: "/assets/HilfulFuzul/daoat and dayi/5.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 16,
    name: "দাওয়াত সম্পর্কিত চল্লিশ হাদিস",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[3],
    description: "দাওয়াত সম্পর্কিত চল্লিশটি গুরুত্বপূর্ণ হাদিসের সংগ্রহ।",
    price: 195.99,
    original_price: 245.99,
    discount: 20,
    stock: 20,
    available: true,
    image: "/assets/HilfulFuzul/daoat and dayi/6.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 17,
    name: "দায়ীর গুণাবলী",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[3],
    description: "দায়ীদের জন্য গুণাবলী ও আদর্শিক মানদণ্ড।",
    price: 200.99,
    original_price: 250.99,
    discount: 20,
    stock: 22,
    available: true,
    image: "/assets/HilfulFuzul/daoat and dayi/9.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 18,
    name: "সত্যের দাওয়াত",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[3],
    description: "সত্যের পথে দাওয়াতের গুরুত্ব।",
    price: 205.49,
    original_price: 260.49,
    discount: 21,
    stock: 25,
    available: true,
    image: "/assets/HilfulFuzul/daoat and dayi/11.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 19,
    name: "দাওয়াত-তাবলীগ শাহাদাত ও  এসলাহ",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[3],
    description: "তাবলীগ, শাহাদাত ও এসলাহের উপর বিস্তারিত আলোচনা।",
    price: 210.99,
    original_price: 265.99,
    discount: 21,
    stock: 24,
    available: true,
    image: "/assets/HilfulFuzul/daoat and dayi/19.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 20,
    name: "দাওয়াতের ফিকির এবং আমলের ময়দান",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[3],
    description: "দাওয়াতের ফিকির এবং আমলের গুরুত্ব ও প্রয়োগ।",
    price: 215.99,
    original_price: 270.99,
    discount: 20,
    stock: 18,
    available: true,
    image: "/assets/HilfulFuzul/daoat and dayi/21.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 21,
    name: "দাওয়াতের কর্ম বিরতি",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[3],
    description: "দাওয়াতের কর্ম এবং বিরতির ব্যবস্থাপনা।",
    price: 220.99,
    original_price: 275.99,
    discount: 20,
    stock: 15,
    available: true,
    image: "/assets/HilfulFuzul/daoat and dayi/29.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 22,
    name: "একটু ভাবুন",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[3],
    description: "একটি অনুপ্রেরণামূলক চিন্তার বই।",
    price: 225.49,
    original_price: 280.49,
    discount: 20,
    stock: 12,
    available: true,
    image: "/assets/HilfulFuzul/daoat and dayi/30.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },

  // Islam and Hedayet
  {
    id: 23,
    name: "আল্লাহ কে?",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[4],
    description: "আল্লাহ সম্পর্কে একটি তথ্যবহুল বই।",
    price: 230.99,
    original_price: 285.99,
    discount: 19,
    stock: 28,
    available: true,
    image: "/assets/HilfulFuzul/islam and hedayet/3.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 24,
    name: "সিরাতুন্নবী",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[4],
    description: "নবী মুহাম্মদ (সাঃ)-এর জীবনী সম্পর্কে একটি বই।",
    price: 235.99,
    original_price: 290.99,
    discount: 19,
    stock: 20,
    available: true,
    image: "/assets/HilfulFuzul/islam and hedayet/14.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 25,
    name: "ইসলাম কাদের ধর্ম",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[4],
    description: "ইসলামের পরিধি ও কাদের জন্য এই ধর্ম।",
    price: 240.49,
    original_price: 295.49,
    discount: 19,
    stock: 22,
    available: true,
    image: "/assets/HilfulFuzul/islam and hedayet/17.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 26,
    name: "মুক্তি কোন পথে",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[4],
    description: "মুক্তির পথ সম্পর্কে একটি দিকনির্দেশনামূলক বই।",
    price: 245.99,
    original_price: 300.99,
    discount: 18,
    stock: 25,
    available: true,
    image: "/assets/HilfulFuzul/islam and hedayet/18.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 27,
    name: "হক আদায়",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[4],
    description: "হক আদায়ের উপর একটি অনুপ্রেরণামূলক বই।",
    price: 250.99,
    original_price: 310.99,
    discount: 19,
    stock: 18,
    available: true,
    image: "/assets/HilfulFuzul/islam and hedayet/20.jpg",
    pdf: "/assets/others/pdf/হক আদায় .pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 28,
    name: "এসো নবী সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের পথে",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[4],
    description: "নবীজীর পথ অনুসরণের উপর একটি নির্দেশনামূলক বই।",
    price: 255.49,
    original_price: 315.49,
    discount: 19,
    stock: 20,
    available: true,
    image: "/assets/HilfulFuzul/islam and hedayet/24.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 29,
    name: "আল্লাহর শাস্তি",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[4],
    description: "আল্লাহর শাস্তি সম্পর্কে একটি গুরুত্বপূর্ণ বই।",
    price: 260.99,
    original_price: 320.99,
    discount: 19,
    stock: 22,
    available: true,
    image: "/assets/HilfulFuzul/islam and hedayet/25.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 30,
    name: "দাওয়াত বিল কুরআন",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[4],
    description: "কুরআনের মাধ্যমে দাওয়াতের উপর একটি নির্দেশনামূলক বই।",
    price: 265.99,
    original_price: 330.99,
    discount: 20,
    stock: 15,
    available: true,
    image: "/assets/HilfulFuzul/islam and hedayet/34.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 31,
    name: "আসবাবে হেদায়েত",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[4],
    description: "হেদায়েতের উপায় সম্পর্কে একটি তথ্যবহুল বই।",
    price: 270.49,
    original_price: 335.49,
    discount: 19,
    stock: 18,
    available: true,
    image: "/assets/HilfulFuzul/islam and hedayet/37.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },

  // Maolana
  {
    id: 32,
    name: "সহযোগী হও প্রতিপক্ষ হয়ো না",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[5],
    description: "সহযোগিতার গুরুত্ব ও প্রতিপক্ষের থেকে নিজেকে রক্ষা।",
    price: 275.99,
    original_price: 340.99,
    discount: 19,
    stock: 20,
    available: true,
    image: "/assets/HilfulFuzul/maolana/7.jpg",
    pdf: "/assets/others/pdf/সহযোগী হও, প্রতিপক্ষ হয়ো না .pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 33,
    name: "দিনের দাওয়াত কিছু প্রশ্ন কিছু বাস্তবতা",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[5],
    description: "দাওয়াত ও দিনের বাস্তবতার উপর আলোচনা।",
    price: 280.99,
    original_price: 345.99,
    discount: 19,
    stock: 18,
    available: true,
    image: "/assets/HilfulFuzul/maolana/8.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 34,
    name: "হাদিয়া এ দাওয়াত",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[5],
    description: "দাওয়াতের উপর একটি উপহারের মতো গ্রন্থ।",
    price: 285.99,
    original_price: 350.99,
    discount: 19,
    stock: 22,
    available: true,
    image: "/assets/HilfulFuzul/maolana/12.jpg",
    pdf: "/assets/others/pdf/হাদিয়ায়ে দাওয়াত.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 35,
    name: "তুহফায়ে দাওয়াত",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[5],
    description: "দাওয়াতের উপর একটি তুহফা গ্রন্থ।",
    price: 290.99,
    original_price: 355.99,
    discount: 18,
    stock: 15,
    available: true,
    image: "/assets/HilfulFuzul/maolana/15.jpg",
    pdf: "/assets/others/pdf/আলোর পথে ( সিরিজ -৪) - Copy.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 36,
    name: "আপনার সেবায় আপনার আমানত",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[5],
    description: "সেবা ও আমানতের গুরুত্বের উপর একটি বই।",
    price: 295.99,
    original_price: 360.99,
    discount: 18,
    stock: 18,
    available: true,
    image: "/assets/HilfulFuzul/maolana/23.jpg",
    pdf: "/assets/others/pdf/আপনার সেবায় আপনার আমানাত.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
  {
    id: 37,
    name: "নবীজির আদর্শ ও আমাদের জীবন বাস্তবতা",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[5],
    description: "নবীজির আদর্শ ও আমাদের জীবন বাস্তবতার উপর একটি বই।",
    price: 300.49,
    original_price: 370.49,
    discount: 19,
    stock: 16,
    available: true,
    image: "/assets/HilfulFuzul/maolana/31.jpg",
    pdf: "/assets/others/pdf/নবীজীর আদর্শ আমাদের জীবন বাস্তবতা.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },

  // Ritiniti
  {
    id: 38,
    name: "অজানা বৈশাখ",
    writer: writers[0],
    publisher: publishers[0],
    category: categories[6],
    description: "বৈশাখের অজানা ইতিহাস ও তথ্য।",
    price: 305.99,
    original_price: 375.99,
    discount: 19,
    stock: 14,
    available: true,
    image: "/assets/HilfulFuzul/ritiniti/16.jpg",
    pdf: "/assets/others/pdf/বাংলা নববর্ষ অজানা বৈশাখ.pdf",
    modelUrl: "/assets/3dmodel/1.glb",
  },
];

export const orders = [
  {
    id: 1,
    name: "Talat Md. Tawfiq Elahi",
    email: "Talat@example.com",
    phone_number: "123456789",
    alt_phone_number: "987654321",
    country: "Bangladesh",
    district: "Dhaka",
    area: "Uttara",
    address_details: "123 Main St",
    total: 250,
    shipping_cost: 10,
    grand_total: 260,
    payment_method: "Credit Card",
    products: [products[0], products[1]],
  },
];

export const orderItems = [
  {
    id: 1,
    order: orders[0],
    product: products[0],
    quantity: 1,
    price: 120,
  },
  {
    id: 2,
    order: orders[0],
    product: products[1],
    quantity: 1,
    price: 130,
  },
];

export const blogs = [
  {
    id: 1,
    title: "কুরআন বোঝার উপায়",
    summary: "কুরআনের গুরুত্ব এবং এর ব্যাখ্যা সম্পর্কে একটি পরিচিতি।",
    date: "2024",
    author: "উস্তাদ আহমদ",
    image: "/assets/others/blog1.jpg",
  },
  {
    id: 2,
    title: "হযরত মুহাম্মদ (সা:) এর জীবনী",
    summary: "হযরত মুহাম্মদ (সা:) এর জীবন এবং তার শিক্ষার গভীর পর্যালোচনা।",
    date: "2024",
    author: "শায়খ ইব্রাহিম",
    image: "/assets/others/blog2.jpg",
  },
  {
    id: 3,
    title: "ইসলামের পাঁচটি স্তম্ভ",
    summary:
      "ইসলামের পাঁচটি স্তম্ভ এবং মুসলিম জীবনে এগুলির গুরুত্ব নিয়ে আলোচনা।",
    date: "2024",
    author: "ড. ফাতিমা",
    image: "/assets/others/blog3.jpg",
  },
];

export const contacts = [
  {
    id: 1,
    name: "Charlie Davis",
    email: "charlie@example.com",
    phone_number: "555555555",
    message: "I would like more information about your products.",
    created_at: "2024-08-27T12:00:00Z",
  },
];
